Repository ramiromarcosmorales/muebleria-hermanos-jota, pull requests merged in 2025-08, with the labels that each got.

#12 feat(index): Creacion estructura index y estilos header-footer
  frontend/assets/css/styles.css
  frontend/assets/img/banner-index.png
  frontend/assets/img/diamante-valores-index.png
  frontend/assets/img/hoja-valores-index.png
  frontend/assets/img/reloj-valores-index.png
  frontend/index.html
Labels: enhancement

#21 feat/ Cambio el boton 'Ver Contactos' a una etiqueta semantica '<a>'
  frontend/index.html
Labels: enhancement

#23 docs: redaccion README.md
  README.md
Labels: documentation

#11 Update productos.html
  frontend/productos.html
Labels: invalid

#24 feat(products): Se agregan estilos y algunas etiquetas html
  frontend/assets/css/styles.css
  frontend/productos.html
Labels: enhancement

#46 feat(productos): renderizado de productos destacados dinamicamente
  frontend/assets/js/featured.js
  frontend/assets/js/products.js
  frontend/index.html
Labels: enhancement

#45 feat(productos): renderizado de productos dinamicamente
  frontend/assets/js/catalog.js
  frontend/productos.html
Labels: enhancement

#50 feat(product): Funcion de routing a detalle de producto
  frontend/assets/css/styles.css
  frontend/assets/js/catalog.js
  frontend/assets/js/featured.js
  frontend/assets/js/product-detail-routing.js
  frontend/producto.html
Labels: enhancement

#51 Feat/formatear precios
  frontend/assets/js/catalog.js
  frontend/assets/js/featured.js
  frontend/assets/js/format-price.js
  frontend/assets/js/product-detail-routing.js
Labels: enhancement
