Repository ramiromarcosmorales/muebleria-hermanos-jota, pull requests merged in 2025-09, with the labels that each got.

#55 Feat/validar datos contacto
  frontend/contacto.html
Labels: enhancement

#54 feat:Se agregaron funcionalidades basicas al carrito
  frontend/assets/js/cart.js
  frontend/assets/js/catalog.js
  frontend/assets/js/product-detail-routing.js
  frontend/contacto.html
  frontend/index.html
  frontend/producto.html
  frontend/productos.html
Labels: enhancement

#64 Feat/product characteristics
  frontend/assets/js/product-detail-routing.js
  frontend/assets/js/products.js
  frontend/producto.html
Labels: enhancement

#61 feat(cart): Renderizado del desplegable del carrito
  frontend/assets/css/styles.css
  frontend/assets/js/cart.js
  frontend/assets/js/catalog.js
  frontend/assets/js/product-detail-routing.js
  frontend/contacto.html
  frontend/index.html
  frontend/producto.html
  frontend/productos.html
Labels: enhancement

#66 feat(styles): Se agregan nuevos estilos y se crea estilos de detalle producto
  frontend/assets/css/styles.css
  frontend/assets/js/catalog.js
  frontend/assets/js/product-detail-routing.js
  frontend/assets/js/products.js
  frontend/contacto.html
  frontend/index.html
  frontend/producto.html
Labels: enhancement

#70 fix(cart): Se mejora la interaccion y se agregan estilos
  frontend/assets/css/styles.css
  frontend/assets/js/cart.js
Labels: bug, enhancement

#53 feat(responsive): responsive design + navbar
  frontend/assets/css/styles.css
  frontend/assets/js/menuHeader.js
  frontend/assets/js/search.js
  frontend/contacto.html
  frontend/index.html
  frontend/producto.html
  frontend/productos.html
Labels: enhancement

#77 fix(template): se agrega comilla faltante
  .github/ISSUE_TEMPLATE/documentation_template.md
Labels: bug

#113 Chore/pipeline
  .github/workflows/ci.yml
  README.md
Labels: chore

#120 Chore/setup front
  README.md
  client/.env.example
  client/.gitignore
  client/public/images/aparador-uspallata.png
  client/public/images/banner-index.png
  client/public/images/biblioteca-recoleta.png
  client/public/images/butaca-mendoza.png
  client/public/images/cama-neuquen.png
  client/public/images/diamante-valores-index.png
  client/public/images/escritorio-costa.png
  client/public/images/hoja-valores-index.png
  client/public/images/logo.svg
  client/public/images/mesa-comedor-pampa.png
  client/public/images/mesa-de-centro-araucaria.png
  client/public/images/mesa-de-noche-aconcagua.png
  client/public/images/reloj-valores-index.png
  client/public/images/silla-de-trabajo-belgrano.png
  client/public/images/sillas-cordoba.png
  client/public/images/sillon-copacabana.png
  client/public/images/sofa-patagonia.png
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/components/Test.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/styles/.gitkeep
  client/src/styles/global.css
  client/src/utils/.gitkeep
  client/src/utils/api.js
  client/src/utils/format-price.js
Labels: enhancement, chore
